// <auto-generated />
using System;
using BillsAccounting.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillsAccounting.DataAccess.Migrations
{
    [DbContext(typeof(BillContext))]
    partial class BillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("BillsAccounting.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColdWaterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectricityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotWaterAndHeatingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Overpayment")
                        .HasColumnType("TEXT");

                    b.HasKey("BillId");

                    b.HasIndex("ColdWaterId");

                    b.HasIndex("ElectricityId");

                    b.HasIndex("HotWaterAndHeatingId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BillsAccounting.Models.BillsComponents.Service", b =>
                {
                    b.Property<int>("SercviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToPay")
                        .HasColumnType("TEXT");

                    b.HasKey("SercviceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BillsAccounting.Models.Bill", b =>
                {
                    b.HasOne("BillsAccounting.Models.BillsComponents.Service", "ColdWater")
                        .WithMany()
                        .HasForeignKey("ColdWaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillsAccounting.Models.BillsComponents.Service", "Electricity")
                        .WithMany()
                        .HasForeignKey("ElectricityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillsAccounting.Models.BillsComponents.Service", "HotWaterAndHeating")
                        .WithMany()
                        .HasForeignKey("HotWaterAndHeatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
